### ISSUE TITLE
Render into div block

### ISSUE THREAD

**Issue by bergos** [zazukoians/trifid-ld#40]
The default template doesn't contain any div block in the [body](https://github.com/zazukoians/trifid-ld/blob/master/data/templates/graph.html#L18) which could be used to extend the template. A div block with a specific should be added an the JS code should be changed to use that div block.

**Comment by retog** [comment]
Hi @bergos, I'm not sure what kind of exension you would like to support. 

Do you mean the server side template should contain a `div` and that the LD2h rendering should only be applied to this block? This would be a backslash as applying the LD2h rendering to the `HTML` element was chosen so that the full page including css and script loading (with systemjs) is determined by the RDF2h matchers. This was introduced with: https://github.com/zazukoians/trifid-ld/commit/68bdee9c4422c3aefebf406d8f1434708faca9ec#diff-5ced1af5a95b47923bb00e0c0cd4d711

The default  matchers are designed to support extensions (overwriting the site-matchers.ttl file) as this is done for example with https://github.com/zazuko/data.admin.ch/blob/master/data/public/rdf2h/site-matchers.ttl.

Please describe the extensions you would like to make so I can show how this can be done better with RDF2h. Reopen the issue if I misunderstood what you would like to have.

**Comment by bergos** [comment]
OK. I didn't look into the root html element, because I didn't expect it there. I'm strongly against this structure of default template, because that means even small changes like adding a logo or a about us link in the footer must be implemented in RDF2h. That raises the barrier for using Trifid-LD. If we have this nice default template, than it should be possible for everyone to use it with minimal changes in the html file.

**Comment by retog** [comment]
The rendering should be customized by RDF2h matchers, not a combination of matchers and some server-side rendering mechanism. All the server-side template does is load the basic scripts and insert the data into the HTML page delivered to the client, the actual rendering happens on the client (we discussed adding RDF2h rendering on the server, but that's another story).

The `graph.html` template has no extension mechanism, so some customizations would have to overwrite this altogether which means that there normally would be a code duplication with Trifid-LD and that some changes in Trifid-LD (e.g. an update of a client-side library) are not propagated to the customizations.

Also as far as I know no mechanism to access the RDF data (e.g. to make the title dependent on some triples). So while it might be marginally easier to add a different static header by modifying `graph.html` for everything else you would have to use RDF2h anyway.
