### ISSUE TITLE
Make content discoverable

### ISSUE THREAD

**Issue by l00mi** [zazukoians/trifid-ld#51]
Provide a generic way to list the contents of a namespace. Each path which is followed by a `/` shall trigger the following query:

```
CONSTRUCT {
  ?sub a ?obj.
}
WHERE {
  ?sub a ?obj.
  FILTER REGEX(STR(?sub), "^{?path}")
}
```

where the path might be something like

```
CONSTRUCT {
  ?sub a ?obj.
}
WHERE {
  ?sub a ?obj.
  FILTER REGEX(STR(?sub), "^http://classifications.data.admin.ch/municipality/")
}
```

We might add a LIMIT which should be fairly high, 10000?

**Comment by ktk** [comment]
While I see what you try to do I'm not sure if this is a smart way to handle it. I would prefer to go into the direction of what we discussed with Zack.

My idea is to have Zack running in `/` on each domain and then provide filters for the main classes within this namespace. This could be extended so that one sees different filters depending on when I access it on `/` or `/municipality/` for example.

Simply returning a list of subjects with a limit of 10'000 does not sound like something I would want. This is for sure if we talk about HTML output, on RDF media types we would have to return something else but there I think using Hydra might make more sense.

**Comment by l00mi** [comment]
This are orthogonal idea, I think we can once add Zack were it makes sense.

But right now we need a way to make at least the Objects discoverable. For the most use cases this will be much less than 10'000, and should load quite fast, even in HTML
It just allows to see what is there. Right now you need to know the data or be SPARQL-iterate.
Any way this should be doable in like 1h of work and will have a huge effect for external people.

Also I don't want this on root for most cases (except probably isli.ch), only on subdirectories like /municipality/, /municipalityversion/ and so on.

**Comment by l00mi** [comment]
Also will this allow bots to learn about the datasets. e.g. http://lodlaundromat.org/basket/

**Comment by bergos** [comment]
Fixed in [this commit](https://github.com/zazukoians/trifid-ld/commit/cd768e5aba88a0e1e40dfef72dd8f5990ea261a3) in the dev branch.
