### ISSUE TITLE
Proxy does not handle https URIs properly

### ISSUE THREAD

**Issue by ktk** [zazukoians/trifid-ld#57]
Given this config for Trifid developer branch:

```json
{
  "baseConfig": "trifid:config-sparql.json",
  "sparqlEndpointUrl": "https://web-sparql-virtuoso.dev.bgdi.ch/sparql",
  "datasetBaseUrl": "https://ld.geo.admin.ch/",
  "staticFiles": {
    "alodFiles": {
      "path": "/",
      "folder": "cwd:data/public"
    }
  }  
}
```

And this URI for testing: http://geotrifid:8080/boundaries/cantons/12 (localhost should probably work as well)

Trifid does the `ASK` for `http`, not `https` as it should according to the `datasetBaseUrl`.

**Comment by ktk** [comment]
Resources to test with:


* https://ld.geo.admin.ch/boundaries/countries/DE
* https://ld.geo.admin.ch/boundaries/countries/CH
* https://ld.geo.admin.ch/boundaries/countries/IT
* https://ld.geo.admin.ch/boundaries/countries/LI
  
* https://ld.geo.admin.ch/boundaries/countries/DE:2016
* https://ld.geo.admin.ch/boundaries/countries/CH:2016
* https://ld.geo.admin.ch/boundaries/countries/IT:2016
* https://ld.geo.admin.ch/boundaries/countries/LI:2016

* https://ld.geo.admin.ch/boundaries/cantons/2
* https://ld.geo.admin.ch/boundaries/cantons/3

**Comment by bergos** [comment]
Fixed with [this commit](https://github.com/zazukoians/camouflage-rewrite/commit/e334f4a7eb99666f0de6bccca4e715850e1bb6a9) in camouflage-rewrite and [this commit](https://github.com/zazuko/trifid/commit/2a9e482cb91e89c3cf3797b18a4f857d8122d74f) in trifid. Patched versions of both packages have been published on npm.
